---
- name: Deploy a jar file
  hosts: ubuntu18
  remote_user: user
  tasks:
    - name: Copy jar file to home directory
      copy:
        src: ./target/devops_calculator-1.0-SNAPSHOT.jar
        dest: ~/
